### ISSUE TITLE
Close to systray doesn't work.

### ISSUE THREAD

**Issue by boromyr** [IgorMundstein/WinMemoryCleaner#12] opened 2023-03-28 12:22 UTC
**Describe the bug**
The window is closed incorrectly, and remains on the desktop as in the photo.
![image](https://user-images.githubusercontent.com/52782032/228234062-e8822e48-e774-483e-b9a4-80d3fa2aeccb.png)

**To Reproduce**
My settings.
![image](https://user-images.githubusercontent.com/52782032/228234113-f631a8cc-d31b-4d13-962d-1564149136ff.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - WMC: 2.0

**Comment by boromyr** [comment] 2023-04-02 19:17
OK, calm down. Did you have problems with "run at startup" ? Sometimes she turns off.

**Comment by IgorMundstein** [comment] 2023-04-03 03:22
> OK, calm down. Did you have problems with "run at startup"? Sometimes she turns it off.

So, Windows doesn't like to run startup apps that require admin privileges. I did a workaround using a scheduled task and a specific Windows registry key.

I need more details. What do you mean by turning it off? The setting, the scheduled task? You need to be more clear about what happened and more details like what Windows you are using, etc.

**Comment by Girofox** [comment] 2023-06-17 09:47
For me setting "Minimized to tray when closed" causes the window to minimize into a small contentless windows in lower left corner. But when I restore the window then and then minimize the window instead of closing it goes into taskbar as intended, after that choosing close works and it is minimized to tray without any trace.

So for me the workaround is:
Minimize window to taskbar -> Restore window from taskbar -> Choose "x" symbol to minimize to tray

**Comment by IgorMundstein** [comment] 2023-07-27 23:06
Fixed. 

Please, review the 2.1 version: https://github.com/IgorMundstein/WinMemoryCleaner/releases/tag/2.1

**Closed by IgorMundstein** 2023-07-27 23:06 UTC
Labels: bug
